FROM sameersbn/gitlab:10.0.3

ENV DB_ADAPTER=mysql2
ENV DB_HOST=mysql
ENV DB_PORT=3306
ENV DB_USER=root
ENV DB_PASS=1234
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

ENV GITLAB_HTTPS=false
ENV SSL_SELF_SIGNED=false

ENV GITLAB_HOST=localhost
ENV GITLAB_PORT=10080
ENV GITLAB_SSH_PORT=10022
ENV GITLAB_SECRETS_OTP_KEY_BASE=Aey1iefoongopoofeibahchaequeelaedoolaitohlohchohthewaethoungohne
ENV GITLAB_SECRETS_SECRET_KEY_BASE=Aey1iefoongopoofeibahchaequeelaedoolaitohlohchohthewaethoungohne
ENV GITLAB_SECRETS_DB_KEY_BASE=Aca3vehaesohraeghiejeeyeibaefaikeiyeithaingowaiquaadohyohdahquou

CMD ["app:start"]